name: supabase_flutter_example
description: Demonstrates how to use supabase_flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
