name: yet_another_json_isolate
description: Package to simplify and improve JSON parsing in isolates by keeping one isolate running per instance.
version: 1.0.4
homepage: https://github.com/supabase-community/json-isolate-dart

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  async: ^2.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
