name: yet_another_json_isolate
description: Package to simplify and improve JSON parsing in isolates by keeping one isolate running per instance.
version: 2.0.0
homepage: https://github.com/supabase-community/json-isolate-dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0
