name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 2.0.4
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  functions_client: ^2.0.0
  gotrue: ^2.3.0
  http: '>=0.13.5 <2.0.0'
  postgrest: ^2.1.0
  realtime_client: ^2.0.0
  storage_client: ^2.0.0
  rxdart: ^0.27.5
  yet_another_json_isolate: ^2.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.17.9
  web_socket_channel: ^2.2.0
