name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 1.9.3
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  functions_client: ^1.3.2
  gotrue: ^1.8.3
  http: '>=0.13.5 <2.0.0'
  postgrest: ^1.3.2
  realtime_client: ^1.1.1
  storage_client: ^1.5.1
  rxdart: ^0.27.5
  yet_another_json_isolate: ^1.1.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.9
  web_socket_channel: ^2.2.0
