name: supabase
description: A dart client for Supabase. This client makes it simple for developers to build secure and scalable products.
version: 2.3.0
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  functions_client: 2.3.2
  gotrue: 2.8.4
  http: '>=0.13.5 <2.0.0'
  postgrest: 2.1.4
  realtime_client: 2.2.1
  storage_client: 2.0.3
  rxdart: '>=0.27.5 <0.29.0'
  yet_another_json_isolate: 2.0.2
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.17.9
  web_socket_channel: '>=2.2.0 <4.0.0'