name: functions_client
description: A dart client library for the Supabase functions.
version: 2.0.0
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/functions_client'
documentation: 'https://supabase.com/docs/reference/dart/functions-invoke'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.4 <2.0.0'
  yet_another_json_isolate: ^2.0.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.4
