name: postgrest
description: PostgREST client for Dart. This library provides an ORM interface to PostgREST.
version: 1.2.3
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/postgrest-dart'

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  http: ^0.13.0
  yet_another_json_isolate: ^1.0.0

dev_dependencies:
  collection: ^1.16.0
  lints: ^1.0.1
  test: ^1.21.4
