name: postgrest
description: PostgREST client for Dart. This library provides an ORM interface to PostgREST.
version: 2.0.1
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/postgrest'
documentation: 'https://supabase.com/docs/reference/dart/select'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.0 <2.0.0'
  yet_another_json_isolate: ^2.0.0
  meta: ^1.9.1

dev_dependencies:
  collection: ^1.16.0
  lints: ^2.1.1
  test: ^1.21.4
