name: gotrue
description: A dart client library for the GoTrue API.
version: 2.14.0
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/gotrue'
documentation: 'https://supabase.com/docs/reference/dart/auth-signup'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.2
  http: '>=0.13.0 <2.0.0'
  jwt_decode: ^0.3.1
  retry: ^3.1.0
  rxdart: '>=0.27.7 <0.29.0'
  meta: ^1.7.0
  logging: ^1.2.0
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  dart_jsonwebtoken: ^2.4.1
  dotenv: ^4.1.0
  lints: ^3.0.0
  test: ^1.16.4
  otp: ^3.1.3

false_secrets:
  - /infra/docker-compose.yml
