name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 2.10.0
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/supabase_flutter'
documentation: 'https://supabase.com/docs/reference/dart/introduction'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  app_links: '>=3.5.0 <7.0.0'
  async: ^2.11.0
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  http: '>=0.13.4 <2.0.0'
  meta: ^1.7.0
  supabase: 2.9.0
  url_launcher: ^6.1.2
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  logging: ^1.2.0
  web: '>=0.5.0 <2.0.0'

dev_dependencies:
  dart_jsonwebtoken: ^2.4.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  path: ^1.8.3

platforms:
  android:
  ios:
  macos:
  web:
  windows:
  linux:

flutter:
