name: realtime_client
description: Listens to changes in a PostgreSQL Database and via websockets. This is for usage with Supabase Realtime server.
version: 2.0.0
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/realtime_client'
documentation: 'https://supabase.com/docs/reference/dart/subscribe'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  http: '>=0.13.0 <2.0.0'
  meta: ^1.7.0
  web_socket_channel: ^2.3.0

dev_dependencies:
  lints: ^2.1.1
  mocktail: ^1.0.0
  test: ^1.16.5
