name: supabase_flutter_example
description: Demonstrates how to use supabase_flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.0.0
  supabase_flutter: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_secure_storage: ^10.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  flutter_secure_storage_web: ^2.0.0
  flutter_secure_storage_linux: ^2.0.0
  flutter_secure_storage_macos: ^4.0.0
  flutter_secure_storage_windows: ^4.0.0

flutter:
  uses-material-design: true
