name: storage_client
description: Dart client library to interact with Supabase Storage. Supabase Storage provides an interface for managing Files stored in S3, using Postgres to manage permissions.
version: 2.4.1
homepage: 'https://supabase.com'
repository: 'https://github.com/supabase/supabase-flutter/tree/main/packages/storage_client'
documentation: 'https://supabase.com/docs/reference/dart/storage-createbucket'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: '>=0.13.4 <2.0.0'
  http_parser: ^4.0.1
  mime: '>=1.0.2 <3.0.0'
  retry: ^3.1.0
  meta: ^1.7.0
  logging: ^1.2.0

dev_dependencies:
  test: ^1.21.4
  lints: ^3.0.0
  path: ^1.8.2
