name: gotrue

on:
  push:
    branches:
      - main
    paths:
      - 'packages/gotrue/**'
      - '.github/workflows/gotrue.yml'
      - '.github/workflows/dart-package-test.yml'

  pull_request:
    paths:
      - 'packages/gotrue/**'
      - '.github/workflows/gotrue.yml'
      - '.github/workflows/dart-package-test.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/dart-package-test.yml
    with:
      package-name: gotrue
      working-directory: packages/gotrue
      needs-docker: true
      docker-compose-dir: infra/gotrue
      test-concurrency: 1

  test-jwks:
    uses: ./.github/workflows/dart-package-test.yml
    with:
      package-name: gotrue
      working-directory: packages/gotrue
      needs-docker: true
      docker-compose-dir: infra/gotrue
      docker-compose-files: docker-compose.yml docker-compose.jwk.yml
      test-concurrency: 1
