name: Auto-Label Issues and PRs

on:
  pull_request:
    types:
      - opened
      - edited
  issues:
    types:
      - opened
      - edited

jobs:
  label:
    uses: supabase/actions/.github/workflows/label-issues.yml@feat/reusable-workflows
    with:
      label_mappings: |
        {
          "gotrue": "auth",
          "auth": "auth",
          "storage": "storage",
          "storage_client": "storage",
          "realtime": "realtime",
          "realtime_client": "realtime",
          "postgrest": "postgrest",
          "functions": "functions",
          "functions_client": "functions",
          "auth_ui": "auth-ui",
          "supabase": "supabase",
          "supabase_flutter": "supabase_flutter"
        }
