name: supabase

on:
  push:
    branches:
      - main
    paths:
      - 'packages/supabase/**'
      - '.github/workflows/supabase.yml'
      - '.github/workflows/dart-package-test.yml'
      - 'packages/functions_client/**'
      - 'packages/gotrue/**'
      - 'packages/postgrest/**'
      - 'packages/realtime_client/**'
      - 'packages/storage_client/**'

  pull_request:
    paths:
      - 'packages/supabase/**'
      - '.github/workflows/supabase.yml'
      - '.github/workflows/dart-package-test.yml'
      - 'packages/functions_client/**'
      - 'packages/gotrue/**'
      - 'packages/postgrest/**'
      - 'packages/realtime_client/**'
      - 'packages/storage_client/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/dart-package-test.yml
    with:
      package-name: supabase
      working-directory: packages/supabase
      test-concurrency: 1
      melos-no-flutter: true
